- name: Copy CONGA vhosts.
  include_role:
    name: wcm_io_devops.conga_files
  vars:
    conga_files_base_path: "{{ apache_sites_available }}"
    conga_files_handlers: [ restart apache ]
    conga_files_files: "{{ conga_files_paths | select('match', 'vhosts.d/') | list }}"
    conga_files_directories: []
    conga_files_strip: 'vhosts.d/'
    conga_files_owner: "{{ apache_config_owner }}"
    conga_files_group: "{{ apache_config_group }}"

- name: Enable CONGA sites.
  command: "a2ensite {{ item | basename }}"
  args:
    creates: "{{ apache_sites_enabled }} /{{ item | basename }}"
  with_items: "{{ conga_files_paths | select('match', 'vhosts.d/.*') | list }}"
  when: not conga_aem_dispatcher_restricted_mode
  notify:
    - restart apache
