---
# _apache_version variable was determined during os family specific setup
- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- name: Enable Apache modules required by CONGA role.
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ conga_config.httpd.modules }}"
  when:
    - conga_config.httpd is defined
    - conga_config.httpd.modules is defined
    - not conga_aem_dispatcher_restricted_mode
  notify:
    - restart apache

# The CONGA configs still use 2.2 auth syntax so we need to enable the compat module for 2.4+
- name: Enable Apache access_compat module for Apache 2.4.
  apache2_module:
    name: access_compat
    state: present
  when:
    - "apache_version.split('.')[1] >= '4'"
    - not conga_aem_dispatcher_restricted_mode
  notify:
    - restart apache
